// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByVMaAGp0QuypGzFeux9dArZWlYoiIuRg',
    appId: '1:752880917133:web:7ecbd3d816995df10520c4',
    messagingSenderId: '752880917133',
    projectId: 'unisnack-fd6ff',
    authDomain: 'unisnack-fd6ff.firebaseapp.com',
    storageBucket: 'unisnack-fd6ff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC4ZAoKq0e9qWEWW7FMeiw8fReADiyAjE',
    appId: '1:752880917133:android:b33a431d028704d50520c4',
    messagingSenderId: '752880917133',
    projectId: 'unisnack-fd6ff',
    storageBucket: 'unisnack-fd6ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOT1AmomliJVg3T9OGSqffK43ECzwQ_Qg',
    appId: '1:752880917133:ios:5a215013813a6f590520c4',
    messagingSenderId: '752880917133',
    projectId: 'unisnack-fd6ff',
    storageBucket: 'unisnack-fd6ff.firebasestorage.app',
    iosBundleId: 'com.example.unisnack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOT1AmomliJVg3T9OGSqffK43ECzwQ_Qg',
    appId: '1:752880917133:ios:5a215013813a6f590520c4',
    messagingSenderId: '752880917133',
    projectId: 'unisnack-fd6ff',
    storageBucket: 'unisnack-fd6ff.firebasestorage.app',
    iosBundleId: 'com.example.unisnack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByVMaAGp0QuypGzFeux9dArZWlYoiIuRg',
    appId: '1:752880917133:web:8ced5a24a142005e0520c4',
    messagingSenderId: '752880917133',
    projectId: 'unisnack-fd6ff',
    authDomain: 'unisnack-fd6ff.firebaseapp.com',
    storageBucket: 'unisnack-fd6ff.firebasestorage.app',
  );
}
